# Mosquitto Broker Configuration

# MQTT estándar (ESP32)

# Puerto: 1883
# Protocolo: MQTT sobre TCP (sin cifrado)
# Nota: el tráfico viaja en texto plano, por lo que debe usarse solo en entornos locales controlados

listener 1883
allow_anonymous true

# MQTT sobre WebSockets (Control Web)

# Puerto: 9001
# Protocolo: MQTT sobre WebSockets
# Contexto técnico: los navegadores NO soportan MQTT nativo (TCP), por lo que se utiliza WebSockets como puente
# Resultado: permite comunicación en tiempo real entre el broker y la interfaz web

listener 9001
protocol websockets
allow_anonymous true

# NO USAR EN PRODUCCIÓN, SOLO DESARROLLO Y RED LOCAL