# Configuración del broker MQTT Eclipse Mosquitto

# Listener para MQTT estándar (ESP32)
listener 1883
allow_anonymous true

# Listener WebSockets (Control Web)
listener 9001
protocol websockets
allow_anonymous true