# CONFIGURACIÓN DEL BROKER MQTT ECLIPSE MOSQUITTO

# MQTT sobre TCP (ESP32)
listener 1883
allow_anonymous true

# MQTT sobre WebSockets (Control Web)
listener 9001
protocol websockets
allow_anonymous true